// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionMetadataSummary } from "./SessionMetadataSummary";
import type { SessionStartedBy } from "./SessionStartedBy";
import type { SessionWorktreeMetadata } from "./SessionWorktreeMetadata";

export type HapirSessionMetadata = { path: string, host: string, version: string | null, name: string | null, os: string | null, summary: SessionMetadataSummary | null, machineId: string | null, claudeSessionId: string | null, codexSessionId: string | null, geminiSessionId: string | null, opencodeSessionId: string | null, tools: Array<string> | null, slashCommands: Array<string> | null, homeDir: string | null, happyHomeDir: string | null, happyLibDir: string | null, happyToolsDir: string | null, startedFromRunner: boolean | null, hostPid: number | null, startedBy: SessionStartedBy | null, lifecycleState: string | null, lifecycleStateSince: number | null, archivedBy: string | null, archiveReason: string | null, 
/**
 * Can be null or absent
 */
flavor?: string | null, worktree: SessionWorktreeMetadata | null, };
