// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RpcCommandResponse = { ok: boolean, stdout: string | null, stderr: string | null, exitCode: number | null, error: string | null, };
