// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RpcTreeNode } from "./RpcTreeNode";

export type RpcGetDirectoryTreeResponse = { ok: boolean, tree: RpcTreeNode | null, error: string | null, };
