// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RpcSlashCommand } from "./RpcSlashCommand";

export type RpcListSlashCommandsResponse = { ok: boolean, commands: Array<RpcSlashCommand> | null, error: string | null, };
