// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RpcDirectoryEntry } from "./RpcDirectoryEntry";

export type RpcListDirectoryResponse = { ok: boolean, entries: Array<RpcDirectoryEntry> | null, error: string | null, };
