// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RpcTreeNode = { name: string, path: string, type: string, size: number, modified: number | null, children: Array<RpcTreeNode> | null, };
