// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentFlavor } from "./AgentFlavor";
import type { SessionWorktreeMetadata } from "./SessionWorktreeMetadata";
import type { SummaryText } from "./SummaryText";

export type SessionSummaryMetadata = { name: string | null, path: string, machineId: string | null, summary: SummaryText | null, flavor?: AgentFlavor | null, worktree: SessionWorktreeMetadata | null, };
